name: CI Sample
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Unit Test
        run: mvn clean test
        working-directory: ./sample-api
      - name: Build Docker Container
        run: docker built -t sample-api:TEST
        working-directory: ./sample-api
      - name: Confirm Docker images
        run: docker images
        working-directory: ./sample-api
      - name: Integration Test
        run: mvn clean install -Dmaven.test.skip=true
        working-directory: ./integration-test

