name: CI Sample
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and Unit Test
        run: mvn clean install
        working-directory: ./sample-api
      - name: Build Docker Container
        run: docker build -t sample-api:TEST .
        working-directory: ./sample-api
      - name: Run docker-compose for Integration Test
        run: docker-compose -f ./docker-compose.yml up -d
      - name: Waiting for starting containers
        run: sleep 30
      - name: Confirm docker Container
        run: docker ps -a
      - name: Migration Database
        run: mvn flyway:migrate
        working-directory: ./integration-test
      - name: Integration Test
        run: mvn test-compile failsafe:integration-test
        working-directory: ./integration-test
      - name: Stop docker-compose for Integration Test
        run: docker-compose -f ./docker-compose.yml down --volumes
      - name: Clean Docker images
        run: docker rmi sample-api:TEST
