name: Continuous Integration

on:
  push:
    branches:
      - oracle_error

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: ./.github/actions/setup-java
        with:
          java-version: '17'
          java-distribution: 'corretto'

      - name: Unit Test
        run: mvn clean test -Duser.language=ja -Duser.country=JP -Duser.timezone=Asia/Tokyo
        working-directory: ./sample-api
