name: Continuous Integration
on: [push]
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and Unit Test
        run: mvn clean install
        working-directory: ./sample-api

      - name: Containerize Application
        run: docker build -t sample-api:TEST .
        working-directory: ./sample-api

      - name: Integration Test
        run: mvn -P integration-test clean verify
        working-directory: ./integration-test

      - name: Clean up Docker images
        if: always()
        run: docker rmi sample-api:TEST
        continue-on-error: true
